extends Node

var is_dragging = false


enum PARTY_TYPE {PATIENT, NORMAL, IMPATIENT, PICKY, CRITIC}
enum PARTY_COLOR {YELLOW, RED, BLUE, GREEN}
enum PARTY_COLOR_ORG {FULL, SYMMETRICAL, RANDOM}


enum TimeOfDay {OPEN, BREAKFAST_RUSH, NORMAL, LUNCH_RUSH, AFTERNOON_LULL, DINNER_RUSH, CLOSING_TIME, CLOSED}
##minor impact on 
enum SERVICE_SPEED {EXTREMELY_SLOW, SLOW, NORMAL, FAST, EXTREMELY_FAST}

enum LEVEL_TYPE {NORMAL, BOSS, VDAY, CHRISTMAS, THANKSGIVING, HALLOWEEN}


enum HIGHLIGHT {WORLD, TABLE, SUBMIT_ORDER, WATER, PICKUP_ORDER, PICKUP_FOOD, DELIVER_FOOD, DELIVER_WATER, CHECK, DIRTY_DISHES, DISHES_TRAY, MOP, MOP_FLOOR, BABY_SEAT, DELIVER_BABY_SEAT, CUSTOMER_LEAVING}
var item_types = ["NOTHING", "ORDER", "FOOD", "WATER", "DIRTY_DISHES", "MOP", "BABY_SEAT"]
enum CLOSE_CONDITION {NONE, IGNORE, CLICK_ON, HOVER_OVER_NEXT}
enum OPEN_CONDITION {NONE, PREVIOUS_TUTORIAL}
enum GRAPHICAL_TO_SHOW {BOSS, ASSISTANT}
enum INSTANCE {CONTINUE, PAUSE_CLOCK_UNTIL_COMPLETE, PAUSE_EVERYTHING_UNTIL_COMPLETE}
enum TIMER_NAMES {ORDERING, WAIT_FOR_FOOD, EATING, CUSTOMER_LEAVING, NOTHING}


enum GameStatus {MENU, PLAYING, PAUSED}
enum SoundType {SFX, MUSIC, VOICE}



const cooking_time : float = 5.0
# max consts
const MAX_CUSTOMERS_PER_TABLE = 4
#\/ redundant but can be used for scoping spawns minimum
const MIN_CUSTOMERS_PER_TABLE = 1
const MAX_TABLES = 8
const GAME_VERSION = "0.1.0"
const length_of_day = 1440.0
